set(LOCAL_INC_DIR
  ${OSPREY_SRC_DIR}/../libspin
  ${OSPREY_SRC_DIR}/include/gnu
  )
set(LOCAL_DEF -DHAVE_SYS_STAT_H=1
  -DHAVE_STDLIB_H=1
  -DHAVE_STRING_H=1
#  -DHAVE_CONFIG_H=1
  )
set(LOCAL_COMPILER_OPT )
set(LOCAL_C_OPT )
set(LOCAL_CPP_OPT )
