set(LOCAL_INC_DIR
  ${OSPREY_SRC_DIR}/../libspin
  ${OSPREY_SRC_DIR}/libdwarf/libdwarf
#  ${OSPREY_SRC_DIR}/gnu/include
  ${BUILD_DIR}
  )
set(LOCAL_DEF
#  -DIN_GCC
#  -DHAVE_CONFIG_H
#  -DFRONT_END
#  -DUSE_DECL_SRCPOS
  -DFE_GNU_4_2_0
#  -DNEW_SYMTAB

#  -DFRONT_END_C
#  -DCFE -DCIL
#  -DDO_IL_LOWERING=0
#  -DNO_USR_INCLUDE=TRUE
#  -DAUTOMATIC_TEMPLATE_INSTANTIATION=0
#  -DINSTANTIATION_BY_IMPLICIT_INCLUSION=0
#  -DBACK_END_IS_C_GEN_BE=0
#  -DMONGOOSE_CIF

#  -DSGI_RAG_BACKEND
 # -DSGI_MONGOOSE
 # -DHANDLE_PRAGMA_WEAK
 # -DMIPSEL
 # -DNEW_INITIALIZER
 # -DIs_True_On
 # -DInsist_On
 # -DDEBUG=1
 # -DCHECKING=1
  -DGPLUSPLUS_FE
)

set(LOCAL_COMPILER_OPT )
set(LOCAL_C_OPT )
set(LOCAL_CPP_OPT )
